import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '@/redux/provider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Dradha',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}


// import { AppProps } from 'next/app';
// import { Provider } from 'react-redux';
// import { store } from './redux/store';

// function App({ Component, pageProps}: AppProps){

//     return (
//         <Provider store={store}>
//             <Component {...pageProps} />
//         </Provider>
//     );
// }

// export default App;