import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import NextAuthProvider from '@/app/NextAuthProvider'

import './globals.css'
import NavBar from '@/components/common/NavBar/NavBar'

const inter = Inter({ subsets: ['latin'] })
import themeGetter from "@/utilities/helpers/themeGetter";

export const metadata: Metadata = {
  title: 'Dradha',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  Session
}: {
  children: React.ReactNode
  Session: any
}) {
    const theme = themeGetter();
    return (
        <html lang="en" className={theme}>
            <body className={inter.className}>
                <NextAuthProvider session={Session}>
                    {children}
                  </NextAuthProvider>
            </body>
        </html>
  )
}